version: "3.3"
services:
  frontend:
    container_name: frontend-react-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - /app/node_modules